### PR TITLE
forms.show_balloon() first prototype [forms module]

### PR DESCRIPTION
**Pull request by jmcouffin**
> first hint from Konstantin (https://github.com/nodatasheet)

image

### CODE REVIEW

**Comment by jmcouffin** [comment]
@thumDer Care to test and improve?

**Comment by jmcouffin** [comment]
@alexdaversa Care to test and improve?

**Comment by jmcouffin** [comment]
Tested
Basic implementation could be pimped adding support for more complex content including xaml layout handling

**Comment by saurabhsjha** [comment]
Tests.pulldown\Forms Module Tests.pushbutton\script.py", line 41, in <module>
NameError: name 'result_item_result_clicked' is not defined

**Comment by jmcouffin** [comment]
> Tests.pulldown\Forms Module Tests.pushbutton\script.py", line 41, in NameError: name 'result_item_result_clicked' is not defined

without this specific code, hard to tell.

**Comment by jmcouffin** [comment]
> when i trying " forms.show_balloon("my header", "Lorem ipsum", tooltip='tooltip', group='group', is_favourite=True, is_new=True, timestamp = '2019-01-01 00:00:00', click_result = forms.result_item_result_clicked)"

you are right, the example was of, I forgot to indicate that the Timestamp needed to be of type 'date'

converting the string to date like so:

```python
date = '2019-01-01 00:00:00'
date = datetime.datetime.strptime(date, '%Y-%m-%d %H:%M:%S')
```

or using `datetime.datetime.now()` dos the trick

**Comment by jmcouffin** [comment]
and thanks @saurabhsjha for giving it a try

**Comment by jmcouffin** [comment]
I also fixed the unit test.
Wait for the next wip

**Pull request merged**
