### PR TITLE
added @Inspect: ListDWGs, LinesPerViewCounter

### PR DESCRIPTION
**Pull request by frederic-beaupere**
Hi Ehsan, 
here my first pyRevit test pull request.
Let me know if I need to change anything about 
the license/credits thing - not too sure on that topic. (-:
Best, 
Frederic

### CODE REVIEW

**Comment by eirannejad** [comment]
Thanks a lot Frédéric,
I merged this into a new branch and will run some test and will merge back into the master. I'll keep you posted on the changes if any.

Cheers

**Comment by frederic-beaupere** [comment]
Sure, you're welcome!
Once they are merged I will PR two more that I prepared this evening..

Cheers

**Comment by eirannejad** [comment]
Done. Moved `List DWG` to under `Project > Links` button and cleaned up the scripts for more legible output. You can import `print_md` from `scriptutils` and use markdown syntax for simple formatting

**Comment by frederic-beaupere** [comment]
Nice - thanks! I will check out print_md - sounds great!

**Pull request merged**
