### PR TITLE
Feature/preflight

### PR DESCRIPTION
**Pull request by jmcouffin**
Hi there, 
Worked a bit on the structure. 
I added the RVT links count and list and also the pinned status count.
Got a bit of trouble making the treshold function work: 

- if not all links pinned red
- if all links pinned green. 
The logic behind the threshold function is not flexible enough in itself to allow for such cases without having to work around it IMHO @davidvadkerti 

I think that organizing the report in a more classical way would be having it listed by themes: 
image

I have left some output.print_md uncomented to test purposes.

Also, having it in two different setupp prospect: 

1. the ui to setup the type of model check with a list of items to be checked (sheets, links, ...) then being able to save it in the revit file or on the computer
2. then a single click for the default _ a bit like the shift click.
3. I would definitely separate all the checks from the displying part of the report.

Could you help with the structure @eirannejad, you are more used to coding complex things than I

### CODE REVIEW

**Comment by jmcouffin** [comment]
I put some more work in in with my last commit: 
image

**Comment by jmcouffin** [comment]
added refplane count and fixed french version
image

**Comment by jmcouffin** [comment]
I'd be interested getting a first feedback from you @eirannejad @davidvadkerti

**Comment by eirannejad** [comment]
Merged into `pr/1103` for review. Thank you so much @jmcouffin

**Comment by eirannejad** [comment]
I think this is good. I'm merging into develop and we can continue improvements further. I'll also add the `author` name in the preflight check selector window

**Comment by jmcouffin** [comment]
Cool. I plan on adding much more based on our qc dynamo script. Will try to
add all the data from links as well.
Is there a way to get the first check checked by default. Couldn't find a
way in the documentation.

Le ven. 8 janv. 2021 19:33, Ehsan Iran-Nejad <notifications@github.com> a
écrit :

**Comment by jmcouffin** [comment]
I mean in  the check selector

Le ven. 8 janv. 2021 19:36, Jean-Marc COUFFIN <jmcouffin@gmail.com> a
écrit :

**Comment by jmcouffin** [comment]
@eirannejad Could you help me a bit on understanding the process for what's following. You merged it to develop. Do I have access to this branch, can I fork it and push PR to it and continue development from there? I am not so familiar with the whole process and I don't want to mess things up.

**Comment by jmcouffin** [comment]
@eirannejad Could you help me a bit on understanding the process for what's
following. You merged it to develop. Do I have access to this branch, can I
fork it and push PR to it and continue development from there? I am not so
familiar with the whole process and I don't want to mess things up.


Le ven. 8 janv. 2021 à 19:37, Jean-Marc COUFFIN <jmcouffin@gmail.com> a
écrit :

**Comment by eirannejad** [comment]
@jmcouffin Oh yeah! All the repo is open so you can fork and 'checkout' any of the branches you want. I usually follow [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) so being familiar with that helps working together better.

Make a branch for the feature or improvements you are working on and continue sending PRs. Keeping the PRs small helps me merge them faster as well.

This is all the usual git collaboration flow. Nothing too specific to pyRevit codebase

**Comment by jmcouffin** [comment]
> @jmcouffin Oh yeah! All the repo is open so you can fork and 'checkout' any of the branches you want. I usually follow [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) so being familiar with that helps working together better.
> 
> Make a branch for the feature or improvements you are working on and continue sending PRs. Keeping the PRs small helps me merge them faster as well.
> 
> This is all the usual git collaboration flow. Nothing too specific to pyRevit codebase

I am not quite there yet in terms of Git Flow. 
I did messup things on my computer with github desktop a few minutes ago. 
I swithced branch from feature/preflight to develop and could not go back. Deleted everything locally and got the develop branch back on my computer wut I got this error and cannot launch pyrevit in revit now
image

**Comment by jmcouffin** [comment]
I manage to get it back together properly I guess, from my own branch
`pyrevit clone pf2  --dest=C:\pyRevit\PFtake2 --source=https://github.com/jmcouffin/pyRevit.git --branch=feature/preflight`

**Comment by jmcouffin** [comment]
I tried many ways, the develop branch does not load as per 
image
@eirannejad

**Comment by eirannejad** [comment]
You need to recompile all the binaries when you are on `develop`. I just committed the compiled binaries and you can update your `develop` from mine.

**Comment by jmcouffin** [comment]
Will do, thanks!
Thanks a lot

Le mar. 12 janv. 2021 18:34, Ehsan Iran-Nejad <notifications@github.com> a
écrit :

**Comment by eirannejad** [comment]
@jmcouffin The selector window now looks like this

Screen Shot 2021-01-15 at 9 22 26 AM

**Comment by jmcouffin** [comment]
Thanks, I'll check it out.
If David does not want to contribute I will need to be added as author as
well 😀

Le ven. 15 janv. 2021 18:23, Ehsan Iran-Nejad <notifications@github.com> a
écrit :

**Comment by eirannejad** [comment]
Ok would you mind expanding the description on your model checker? The description is basically the docstring for the class

``` python
class ModelChecker(PreflightTestCase):
    """Revit Model Quality Checker"""
# ...
```

**Comment by jmcouffin** [comment]
> Ok would you mind expanding the description on your model checker? The description is basically the docstring for the class
> 
> ```python
> class ModelChecker(PreflightTestCase):
>     """Revit Model Quality Checker"""
> # ...
> ```

see https://github.com/eirannejad/pyRevit/pull/1127

**Comment by davidvadkerti** [comment]
> I put some more work in in with my last commit:
> image

Hi, just to explain my original intent(don't know whether it is relevant): the reason why I packed all "squares" together was to quickly spot red squares without much scrolling. 

Hopefully I will have some time to contribute to this tool. You've done a lot since I wasn't here :)

**Comment by jmcouffin** [comment]
I do get it. And it is my intention to bring it back together as well. I
did spread it in sections to make it more understandable in terms of ui and
coding as well. I was thinking about making blocks of analysis per category
with a' easy to read section title: section title+analytics squares, then
another one.
I am still not satisfied with the way charts behave (the legend in
particular).
I plan on adding more squares and sections then take care of the charts
issue as it is something a bit out of my usual playground.

Le lun. 8 févr. 2021 22:20, davidvadkerti <notifications@github.com> a
écrit :

**Comment by jmcouffin** [comment]
And excellent job BTW. It gave shape to something I have been working on
in  dynamo for quite a bit.
Next big step. Collect the same data for links and then push all this data
neatly in a db for further chronological analysis

Le lun. 8 févr. 2021 22:20, davidvadkerti <notifications@github.com> a
écrit :

**Comment by davidvadkerti** [comment]
In the [tool](https://bitbucket.org/davidvadkerti/customtools/src/master/CustomTools.tab/Batch.panel/Model%20checker.splitpushbutton/ModelChecker.pushbutton/) in my extension all results are logged and then can be analysed in power BI dashboard. I removed this part of code to make the initial pull request easier. I wanted to add this feature later.
There is also another version of  this script adapted for use in [Revit Batch Processor](https://github.com/bvn-architecture/RevitBatchProcessor). Then you can run it automaticaly on all of your central files every evening and put [results in Power BI](https://youtu.be/dl9iA62TTWY). I tried to use pyRevit Run but unfortunately I wasn't capable of doing it.

**Comment by jmcouffin** [comment]
I've looked at it before going into preflight customization, and I understand the need. I'd rather send the data to a gsheet of an online db though for practical reasons: no need to update the pbi ou google dashboard as the data would be live linked. That is the way I do it with our qc dynamo script. slightly more streamlined. When should find a way to make the script work with RBP or pyrevit run as well for that matter. Thoughts, @eirannejad ? 
You set of tools are fantastic @davidvadkerti.

**Pull request merged**
