### PR TITLE
LibGit2Sharp CredentialsProvider fix

### PR DESCRIPTION
**Pull request by kekejun**
We met the error when using the pyRevit CLI tool, trying to update our own extensions:

`Error: Could not load file or assembly 'LibGit2Sharp, Version=0.29.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Run with "--debug" option to see debug messages `

Since the **CloneOptions** from **LibGit2Sharp** version 0.29.0.0 has no more property **CredentialsProvider**, I adjusted the line to set it.

### CODE REVIEW

**Comment by jmcouffin** [comment]
Yep, in the wip installers, under actions, you can find the installer with the mismatch fix, but I went with the option to revert to 26.2. I had not time to fiddle.

Before I merge your PR,
Can I ask how you compiled bin/pyRevitLabs.Common.dll? @kekejun

**Comment by kekejun** [comment]
> Yep, in the wip installers, under actions, you can find the installer with the mismatch fix, but I went with the option to revert to 26.2. I had not time to fiddle.
> 
> Before I merge your PR, Can I ask how you compiled bin/pyRevitLabs.Common.dll? @kekejun

Hi @jmcouffin , thanks for the quick response. I did that in VS by rebuilding the pyRevitLabs.Common project after modifying the line, but it was switched to Debug Configuration instead of Release. Please tell me if I did anything wrong.

**Comment by jmcouffin** [comment]
Reviewed, this look OK.
I will merge it and you will be able to try it under the actions tab with the WIP Installers @kekejun 
Thank you for the PR

**Comment by kekejun** [comment]
There is an error in action, I think it's because I forked with master, where the version in pyRevitLabs.PyRevit is 0.29. should I make another PR @jmcouffin ?

**Comment by jmcouffin** [comment]
Please do, @kekejun 
and branch from develop first
Thank you

**Pull request merged**
