### PR TITLE
Feature/show view range

### PR DESCRIPTION
**Pull request by thumDer**
implementation of #2061

### CODE REVIEW

**Comment by thumDer** [comment]
Need to finalize the ui with a simple control to dinamically show the actual elaevation values

**Comment by thumDer** [comment]
> Let me know when you feel it is ready for review @thumDer

Technically it is ready, the core functionality is working, can be tested. I could use some inputs for the ui, though... I'm a bit stuck.

**Review by jmcouffin — COMMENTED** [review]
I did some UI and cosmetic changes. 
It seems the windows is not reporting distances for view ranges _ not implemented?  Looking quickly at the code, it remains at None Line https://github.com/thumder/pyrevit/blob/d090a31116f70bf9b9219a0ead5aed87356784b7/extensions/pyRevitTools.extension/pyRevit.tab/Toggles.panel/toggles3.stack/ViewRange.pushbutton/script.py#L203 
and following

**Comment by jmcouffin** [comment]
image

**Comment by jmcouffin** [comment]
All in all a great tool.
If you could implement the levels for cut planes, that would wrap the gift.
UI is fine. Good job @thumDer

**Comment by thumDer** [comment]
> I did some UI and cosmetic changes. It seems the windows is not reporting distances for view ranges _ not implemented? 

yep that is still a TODO, but shouldn't take that long. Let me finish it, and it will be ready to merge.

**Comment by jmcouffin** [comment]
bump ;p @thumDer

**Comment by thumDer** [comment]
It's happening! :) I might replace the wpf grid to a table, and it would be really great to show the (length) units of the elevation. It is extracted from the project units, but showing it is a bit more complicated than I thought.

**Comment by jmcouffin** [comment]
Do you want me to merge this first iteration? @thumDer

**Comment by thumDer** [comment]
I'll try to finish this week with the fine tuning. If I don't have enough time I'll close the PR, and merge it as it is. (If you have no objections, of course.)

**Comment by jmcouffin** [comment]
🪖no onjections. Sir.
Thanks mate

**Comment by thumDer** [comment]
I consider it done

image

**Comment by Robbo1234** [comment]
Hi there, I installed pyRevit v4.8.16.24121 and tested 'Show View Range' in Revit 2021.1.9 and I got this error.

_IronPython Traceback:
Traceback (most recent call last):
 File "C:\Program Files\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Toggles.panel\toggles3.stack\ViewRange.pushbutton\script.py", line 10, in <module>
ImportError: Cannot import name SelectionChangedEventArgs

Script Executor Traceback:
IronPython.Runtime.Exceptions.ImportException: Cannot import name SelectionChangedEventArgs
 at IronPython.Runtime.Importer.ImportFrom(CodeContext context, Object from, String name)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by thumDer** [comment]
Yes, that is what I forgot to do to disable the script in versions lower than 2023, because that specific event was introduced in that version. I will include some warning, but it won't work in those versions. 😔

**Comment by Robbo1234** [comment]
Thanks, Btw, I launched Revit 2023.1 to test 'Show View Range' and I'm getting this PyLoader- Error Loading pyRevit 

image

**Comment by thumDer** [comment]
That seems like a different issue with the pyRevit loader. If it persists please post an issue, with the required information.

**Comment by thumDer** [comment]
@jmcouffin I've doublechecked and it might be possible to make this work in earlier Revit versions without the `SelectionChanged` event, but that will require to abuse the `Idling` event and might behave differently, or have unexpected results. For now I would suggest to only disable the tool in earlier versions with a warning, but I don't know what is the policy about supporting legacy versions, so I would ask you to decide.

**Comment by jmcouffin** [comment]
> Revit 2021.1.9 and I got this erro
@Robbo1234 
You know that 2021 is not supported by Autodesk anymore, right?

**Comment by jmcouffin** [comment]
> `Idling` event

@thumDer I would avoid that.
You could just use the bundle min-version flag:
```yaml
# minimium supported Revit version
min_revit_version: 2023
```
or do it in the tool script itself, but I prefer the use of the flag

There is no particular will to support legacy versions when adding new tools.

**Comment by thumDer** [comment]
I thought that must be a thing, just didn't have time to doublecheck :D I'll update the bundle on the dev branch

**Comment by thumDer** [comment]
done via https://github.com/pyrevitlabs/pyRevit/commit/5c12574ac7f9fdbb0533cc3a917f668a4033592b

**Comment by Robbo1234** [comment]
Yes, I'm aware Autodesk support is always restricted to the last 4 versions
of the product.

**Comment by RevitIRL** [comment]
If Levels are turned off in v/g (our default), I get this:

```
Traceback (most recent call last): 
 File "C:\Users\lionel.KAI-HAWAII\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Toggles.panel\toggles3.stack\ViewRange.pushbutton\script.py", line 128, in context_changed 
 corners = corners_from_bb(level_bbox) 
 File "C:\Users\lionel.KAI-HAWAII\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Toggles.panel\toggles3.stack\ViewRange.pushbutton\script.py", line 95, in corners_from_bb 
 transform = bbox.Transform 
AttributeError: 'NoneType' object has no attribute 'Transform' 
```

Also, I notice the extents of the colored planes match the extents of Level 1 (or maybe the first Level in the model) instead of matching the extents of the view.

**Comment by jmcouffin** [comment]
> If Levels are turned off in v/g (our default), I get this:
> 
> ```
> Traceback (most recent call last): 
>  File "C:\Users\<username>\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Toggles.panel\toggles3.stack\ViewRange.pushbutton\script.py", line 128, in context_changed 
>  corners = corners_from_bb(level_bbox) 
>  File "C:\Users\<username>\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Toggles.panel\toggles3.stack\ViewRange.pushbutton\script.py", line 95, in corners_from_bb 
>  transform = bbox.Transform 
> AttributeError: 'NoneType' object has no attribute 'Transform' 
> ```
> 
> Also, I notice the extents of the colored planes match the extents of Level 1 (or maybe the first Level in the model) instead of matching the extents of the view.

Please create an issue/feature request @RevitIRL 
It will be easier to follow up and prioritize

**Comment by RevitIRL** [comment]
cool :)

https://github.com/pyrevitlabs/pyRevit/issues/2244
https://github.com/pyrevitlabs/pyRevit/issues/2245
https://github.com/pyrevitlabs/pyRevit/issues/2246

**Pull request merged**
