### PR TITLE
Cli extend from private repo

### PR DESCRIPTION
**Pull request by Dre-Tas**
This PR intends to allow the CLI to install extensions stored in private repositories, which you need credentials (username and password) for.

**IMPORTANT**: I haven't been able to test these changes as I can't debug the code! I tried to follow the instructions in the `dev` folder but it didn't work. Can you please either test it or help me doing that?

### CODE REVIEW

**Comment by eirannejad** [comment]
Yummm! Thanks a lot. Let me take a look and will merge soon

**Comment by eirannejad** [comment]
BTW, @Dre-Tas How was the experience reading the code base? is it too complicated to understand what is going on? Just wondering since there is not much documentation.

**Comment by Dre-Tas** [comment]
To be fair I had a quick look at the python extensions, mostly the Extensions command, and I didn't understand much. But that's mostly because I didn't really need to so I spent just 10 minutes on that. I was trying to understand how the cloning part was working from the GUI.

The cli on the other side is quite clear! Overwhelming at the beginning as it's huge, but once you start looking into it's straightforward.
And this is pretty much all I looked at.

In general it is really impressive how you managed to create such a big and complex project. Well done!

**Comment by Dre-Tas** [comment]
After being able to test the code, I realised it wasn't working due to the UsagePattern.txt not recognising the command.
I modified the file and now it's working and it's been tested!

**Comment by eirannejad** [comment]
Merged to pr/811 for review.

**Comment by eirannejad** [comment]
@Dre-Tas Thank you so much for this PR. This is a massively helpful feature that is added.

The PR, however, had a lot of code reformatting included. Also a duplicate dependency (`Nlog`) was added to most projects. pyRevit already has Nlog and is named `pyRevitLabs.NLog` to avoid dependency conflicts with other addons on Revit. I went through the PR line by line and committed the code changes only. I'd rather keep the code formatting consistent with the rest of the code base (e.g. `{` on the same line like ` if () {`). Not a big issue at all but it would make the commit much cleaner and only includes code changes.

I also extended the credentials options to the `pyrevit clone` command so custom and private pyRevit clones can now be deployed as well.

Thank you so much again

**Comment by Dre-Tas** [comment]
I'm really glad I've been able to help!

Sorry about the duplicate dependency...not really sure how that happened! I know I haven't added packages but could have been a VS thing.
As per the formatting...inline `{` in C# is for barbarians, but I'll forgive you. Ahahahahhaa jokin of course! 🤣 

Again, well done with this awesome project and keep up the great work!! I really hope I'll be able to help again.

**Comment by eirannejad** [comment]
Me too. Hope you keep contributing 😃 This feature is going to be super helpful for larger companies

**Comment by jbf1212** [comment]
@Dre-Tas Thank you for this! Question about implementing this - Would each person running the installer need to have their own github username and password to point directly to the private repo or would you generally setup one generic account that's only used for purposes of the install, and keep the credentials in the ps1 installation file?

**Comment by Dre-Tas** [comment]
@jbf1212 you can do both! It depends on where your repo that contains the code for your buttons lives.
If it's on your personal repo than you use your personal creds. If it's on your company's repo then you'd use those creds and the ps1 option.

**Pull request merged**
