### PR TITLE
add theme changed event hook

### PR DESCRIPTION
**Pull request by dosymep**
Need to implement theme-changed event hook.
@jmcouffin, Do you have the right implementation?

### CODE REVIEW

**Comment by jmcouffin** [comment]
This should work but the event is not implemented in the develop branch yet, so it cannot perform. Take a look a my branch https://github.com/jmcouffin/pyRevit/tree/theme-changed_event

**Comment by dosymep** [comment]
I don't know how to import your changes in my repo :) I read your implementation

**Comment by jmcouffin** [comment]
> I don't know how to import your changes in my repo :) I read your implementation

you can work from my branch to improve it ;p

**Comment by jmcouffin** [comment]
@dosymep or create a PR https://github.com/dosymep/pyRevit/compare/theme_changed...jmcouffin:pyRevit:theme-changed_event

**Comment by dosymep** [comment]
I think this change will worsen the user experience

**Pull request closed without merging**
