### PR TITLE
Drop old ipy engines

### PR DESCRIPTION
**Pull request by sanzoghenzo**
This removes the old IronPython engines, leaving only 2.7.11 and 3.4.0.

Note that building the installer fails due to the missing runtime csharp files (moved by 584eda7c83563c81f631bc4dfb79a2267f2317bf).

I also added a workflow to do the build only (`pyrevit build products`) on forks (so that we can ensure everything compiles before submitting a PR).

### CODE REVIEW

**Comment by jmcouffin** [comment]
You want to use which base branch @sanzoghenzo ?
You may want to rebase?

**Comment by sanzoghenzo** [comment]
Thanks for the pointer @jmcouffin, I always forget to set the right branch :sweat_smile: 

I did the work on the develop branch, should I do it on the 4x one?

**Comment by jmcouffin** [comment]
I'd say both, yes please

**Comment by jmcouffin** [comment]
Would you mind trying the installer for the dev 4 branch? @sanzoghenzo

**Pull request merged**
