### PR TITLE
config mode for Get Centroid

### PR DESCRIPTION
**Pull request by thumDer**

### CODE REVIEW

**Comment by jmcouffin** [comment]
Works on 2024 and 2023 on my side.
But you are right, the implementation of the shift click made by @thumDer is slightly different from the common one, as it does not produce the little `dot `next to the tool button.

**Comment by jmcouffin** [comment]
to trigger the little dot, it takes a config.py file in the same folder to take care of the shift+click process.

**Comment by dr3141** [comment]
You are right, @jmcouffin it works! Apologies for the confusion, @thumDer

A 3D element needs to be selected in the model before shift clicking the Get Centroid icon. I was trying to do it without selecting anything first.

**Comment by thumDer** [comment]
I can move the part handling the config to a `config.py` but that way it is not possible to use the selection context anymore I think. But if that solution make more sense to you I can update it.

**Pull request merged**
