### PR TITLE
reorganized code sections + added view template section

### PR DESCRIPTION
**Pull request by jmcouffin**
added: 

- view templates count
- view templates unused count
- conditionnal doughnut display for inplace fam.

reoarganized:

- code sections: sheets, views, schedules
- inplace doughnut location with inplace count
- phases before element count and doughnut

### CODE REVIEW

**Comment by jmcouffin** [comment]
I'd like your opinion @eirannejad 
Would a layout like this be nicer?
image
_it is just a quick cut and paste layout_

**Comment by eirannejad** [comment]
Yeah looks good to me. Honestly you are using this a lot more so I trust your opinion on where and how to display the info

**Comment by eirannejad** [comment]
Merged. Thank you!

**Comment by jmcouffin** [comment]
Thank you @eirannejad. 
I could not imagine myself doing what I am doing right now thanks to the pyrevit framework. And I  am having fun and learning new things_ a ton at the same time. I am confident if we get the preflight checks up to speed like a strong QA qc tool it will help bim practice worry about other more important stuffs.

**Comment by eirannejad** [comment]
Omg yeah I have been wanting to build the preflight into the extensions but never really had a good useful script like yours. Thank you so much for working so hard on this.

**Pull request merged**
