### PR TITLE
Edit Keynotes

### PR DESCRIPTION
**Pull request by DMapes**
I created this by combining two of your tools "Find unused Keynotes" and " Open Current session Journal . If you like it maybe you can add it. Just opens the Keynote.txt associated with the project in Word. I am still very green so any comments would be greatly appreciated.

### CODE REVIEW

**Comment by DMapes** [comment]
Still needs some work.

**Comment by eirannejad** [comment]
@DMapes Sorry. I was really busy this week and didn't get a chance to look a this. I'm looking forward to getting this PR again.

**Comment by DMapes** [comment]
I would appreciate your feedback.

**Comment by eirannejad** [comment]
Dan I modified and added your `Open Keynote file` tool. Here is the updated script. You can get the keynote file address from the `KeynoteTable` class so this makes the script much shorter.

https://github.com/eirannejad/pyRevit/blob/90de5fddc9cf11488b391a93a6e42ad3681fa409/extensions/pyRevitTools.extension/pyRevit.tab/Drawing%20Set.panel/views.stack3/Legends.pulldown/Open%20Keynotes%20File.pushbutton/script.py

**Pull request merged**
