### PR TITLE
New tool: Color Group types

### PR DESCRIPTION
**Pull request by melnikovalex**
Hey Ehsan. 
Please check out the new "Inspect" tool.

It allows to color groups on a view/views, so each group type have certain color. It helps to get rid of unnecessary group types.

Thank you!
(More PRs are comming, trying to split the changes into smaller ones)

### CODE REVIEW

**Comment by eirannejad** [comment]
Hey @melnikovalex 
Thank you so much for the PRs and getting more involved with the project. I got a couple of comments on the general programming style for the pyRevit tools. None of these comments are related to the logic of your tools and is generally geared towards coding style to match with the existing code base and python best practices.

**Comment by eirannejad** [comment]
Try laying out your script as shown below

2019-10-15 11_01_33-script py - pyRevit (Workspace) - Visual Studio Code  Administrator

**Comment by eirannejad** [comment]
Don't import individual types into your script's namespace. Import `DB` and reference by that namespace instead. This results in clearer code and less nameing conflicts

Bad:
`from Autodesk.Revit.DB import FilteredElementCollector, Group, OverrideGraphicSettings, Color, View`

Good
`from Autodesk.Revit import DB`

**Comment by eirannejad** [comment]
Use list, dict and set comprehensions instead of `map` and `filter`. They're faster and more efficient

Bad:
`map(lambda c: blend_color(c), colors_all[:count_1])`

Good:
`[blend_color(x) for x in colors_all[:count_1]]`

**Comment by eirannejad** [comment]
`all` is a builtin function in python. Do not override the values for [builtin functions](https://docs.python.org/2.7/library/functions.html)

Very Bad:
`all = get_all_on_view(v.Id)`

**Comment by eirannejad** [comment]
Use clear names for variables unless it's inside a comprehension expression

Bad:
`for v in views:`

Good:
`for view in views:`

**Comment by eirannejad** [comment]
Lists have builtin `__bool__` implemented. Do not need to check the size for branching

Bad:
`if len(selection) == 0:`

Good:
`if not selection:`

**Comment by eirannejad** [comment]
Use clear names for functions

Bad:
`run(views)`

Good:
`colorize_group_in_views(views)`

**Comment by eirannejad** [comment]
Moved the tool under Groups pulldown. See my revisions [here per comments above](https://github.com/eirannejad/pyRevit/commit/e46e86fcf549bce4a22ee446863aa36aa4a4772d

2019-10-15 11_16_11-Autodesk Revit 2019 2 -  Project1 rvt - 3D View_ {3D}
)

**Comment by eirannejad** [comment]
Install and activate `pylint` on your VSCode (Assuming you are using vscode). It helps a lot cleaning the code to be more pythonic. I learned a lot from pylint

**Comment by Robbo1234** [comment]
Hi Ehsan,

Could there be something similar developed to Colourise Revit Links?

Rob

**Comment by Robbo1234** [comment]
Also, it would be good feature it one could hold shift to reset the Graphic Overrides.

**Comment by Robbo1234** [comment]
Is there a way to control what colours are used when using PyRevit Color Group Types because I tested on some Room Groups and some of the colours looked very similar.

Refer to screenshot:
image

**Comment by Robbo1234** [comment]
Also it would be good if PyRevit Color Group Types worked on selections of Revit Groups as well as views,

**Comment by melnikovalex** [comment]
> 
> 
> Also it would be good if PyRevit Color Group Types worked on selections of Revit Groups as well as views,

Hey @Robbo1234 Rob, thank you for your feedback. Good that you've noticed this bug with colors. It makes no sence, you're right.

I've updated the code here #977

**Pull request merged**
