### PR TITLE
Fixes to work with translated Revit; minor improvements

### PR DESCRIPTION
**Pull request by melnikovalex**
**Framework imporvements**:
7641f7af	Support BuiltInCategories in script `__context__`

There used to be a couple of scripts (Override Dims/Texts) which were using English category name in a `__context__`.  That was making those button always unavailable in non-English Revit. Now it is considering strings started from `OST_` as a BuiltInCategory name.

**Fixes to work with translated Revit**:

7e15da6d	Find Referencing Views
97b1b862	Views tools:

- Add Views to Sheets
- Find Views By Filter

f72432a9	Sheet tools

- Print ordered sheet index
- ReOrder / Increment / Decrement sheet number

cbf469c9	Override VG
e2830f0f	Overrides scripts (Dimension, Text)
a5fa8dc2	Elements of selected Level
bcd15ddb	Pick tool

**UI improvements**:
47310cee and c3ac17a1 CommandSwitchWindow new option: RecognizeAccessKey

There were a problem: CommandSwitchWindow was swallowing first underscore in button names (e.g. with type names it was `ARCDoor_1` instead of `ARC_Door_1`)

There are two commits. 47310cee First I was trying to make it possible to set this options for some of the switches, but it was looking too ugly. c3ac17a1 Finally it is possible to set this options for whole form.

**Misc pyRevit tools imporvements** ba676d28	

Clean ups 46f7aaa

### CODE REVIEW

**Comment by eirannejad** [comment]
- [ ] complete PR review on other modified scripts

**Comment by eirannejad** [comment]
@melnikovalex Does your test model return a `DB.Caetgory` for `DB.BuiltInCategory.OST_Truss`?
```python
from pyrevit improt revit
revit.query.get_category(DB.BuiltInCategory.OST_Truss)
```

**Comment by melnikovalex** [comment]
> ```python
> from pyrevit improt revit
> revit.query.get_category(DB.BuiltInCategory.OST_Truss)
> ```

It returns `None`

For OST_Walls works normally

**Comment by eirannejad** [comment]
@melnikovalex Ran a search and apparently there is a lot of them
```
OST_StackedWalls_Obsolete_IdInWrongRange
OST_MassTags_Obsolete_IdInWrongRange
OST_MassSurface_Obsolete_IdInWrongRange
OST_MassFloor_Obsolete_IdInWrongRange
OST_Mass_Obsolete_IdInWrongRange
OST_WallRefPlanes_Obsolete_IdInWrongRange
OST_StickSymbols_Obsolete_IdInWrongRange
OST_RemovedGridSeg_Obsolete_IdInWrongRange
OST_AssemblyOrigin_Lines
OST_AssemblyOrigin_Planes
OST_AssemblyOrigin_Points
OST_AssemblyOrigin
OST_AnalyticalNodes_Lines
OST_AnalyticalNodes_Planes
OST_AnalyticalNodes_Points
OST_RigidLinksAnalytical
OST_CompassSecondaryMonth
OST_CompassPrimaryMonth
OST_CompassSectionFilled
OST_LightLine
OST_MultiSurface
OST_SunSurface
OST_Analemma
OST_SunsetText
OST_CompassSection
OST_CompassOuter
OST_SunriseText
OST_CompassInner
OST_SunPath2
OST_SunPath1
OST_Sun
OST_SunStudy
OST_StructuralTrussHiddenLines
OST_TrussBottomChordCurve
OST_TrussTopChordCurve
OST_TrussVertWebCurve
OST_TrussDiagWebCurve
OST_Truss
OST_RailingSystemTransitionHiddenLines_Deprecated
OST_RailingSystemTerminationHiddenLines_Deprecated
OST_RailingSystemRailHiddenLines_Deprecated
OST_RailingSystemTopRailHiddenLines_Deprecated
OST_RailingSystemHandRailBracketHiddenLines_Deprecated
OST_RailingSystemHandRailHiddenLines_Deprecated
OST_RailingSystemPanelBracketHiddenLines_Deprecated
OST_RailingSystemPanelHiddenLines_Deprecated
OST_RailingSystemBalusterHiddenLines_Deprecated
OST_RailingSystemPostHiddenLines_Deprecated
OST_RailingSystemSegmentHiddenLines_Deprecated
OST_RailingSystemHiddenLines_Deprecated
OST_StairStringer2012HiddenLines_Deprecated
OST_StairTread2012HiddenLines_Deprecated
OST_StairLanding2012HiddenLines_Deprecated
OST_StairRun2012HiddenLines_Deprecated
OST_Stairs2012HiddenLines_Deprecated
OST_OBSOLETE_ElemArrayHiddenLines
OST_StructuralFramingSystemHiddenLines_Obsolete
OST_StructSubConnections
OST_StructConnectionNobleWarning
OST_StructConnectionFailed
OST_StructConnectionStale
OST_StructWeldLines
OST_FabricAreaTags
OST_CoverType
OST_Cage
OST_AreaReinXVisibility
OST_AreaReinSketchOverride
OST_RebarLines
OST_RebarSketchLines
OST_OBSOLETE_FabricationPartsTmpGraphicDropDrag
OST_FabricationPartsTmpGraphicDrag
OST_OBSOLETE_FabricationPartsTmpGraphicDrop
OST_FabricationPartsTmpGraphicEnd
OST_LayoutNodes
OST_FabricationServiceElements
OST_LayoutPathBase_Pipings
OST_NumberingSchemas
OST_DivisionRules
OST_DivisionProfile
OST_SplitterProfile
OST_GraphicalWarning_OpenConnector
OST_PipingSystem_Reference
OST_DuctSystem_Reference
OST_ParamElemElectricalLoadClassification
OST_DataPanelScheduleTemplates
OST_SwitchboardScheduleTemplates
OST_BranchPanelScheduleTemplates
OST_ConduitStandards
OST_ElectricalLoadClassifications
OST_ElectricalDemandFactorDefinitions
OST_HVAC_Load_Schedules
OST_HVAC_Load_Building_Types
OST_HVAC_Load_Space_Types
OST_LayoutPath_Bases
OST_WireTemperatureRatings
OST_WireInsulations
OST_WireMaterials
OST_HVAC_Zones_Reference
OST_HVAC_Zones_InteriorFill
OST_Fluids
OST_PipeSchedules
OST_PipeMaterials
OST_PipeConnections
OST_EAConstructions
OST_RouteCurveBranch
OST_RouteCurveMain
OST_RouteCurve
OST_GbXML_Opening
OST_GbXML_SType_Underground
OST_GbXML_SType_Shade
OST_GbXML_SType_Exterior
OST_GbXML_SType_Interior
OST_GbXMLFaces
OST_PipeFittingInsulation
OST_FlexPipeCurvesInsulation
OST_PipeCurvesInsulation
OST_DuctFittingLining
OST_DuctFittingInsulation
OST_FlexDuctCurvesInsulation
OST_DuctCurvesLining
OST_DuctCurvesInsulation
OST_FlexPipeCurvesContour
OST_PipeCurvesContour
OST_ElectricalDemandFactor
OST_ElecDistributionSys
OST_ElectricalVoltage
OST_ElectricalCircuitTags
OST_FlexDuctCurvesContour
OST_DuctCurvesContour
OST_ConnectorElemZAxis
OST_ConnectorElemYAxis
OST_ConnectorElemXAxis
OST_ConnectorElem
OST_BridgeBearingTags
OST_BridgeGirderTags
OST_BridgeFoundationTags
OST_BridgeDeckTags
OST_BridgeArchTags
OST_BridgeCableTags
OST_BridgeTowerTags
OST_BridgePierTags
OST_BridgeAbutmentTags
OST_BridgeBearingHiddenLines
OST_BridgeGirderHiddenLines
OST_BridgeFoundationHiddenLines
OST_BridgeDeckHiddenLines
OST_BridgeArchHiddenLines
OST_BridgeCableHiddenLines
OST_BridgeTowerHiddenLines
OST_BridgePierHiddenLines
OST_BridgeAbutmentHiddenLines
OST_DesignOptions
OST_DesignOptionSets
OST_Revisions
OST_EditCutProfile
OST_DecalType
OST_DecalElement
OST_SpotSlopesSymbols
OST_SpotCoordinateSymbols
OST_StructuralConnectionHandlerTags_Deprecated
OST_HostFinTags
OST_Tags
OST_MEPSpaceReference
OST_MEPSpaceInteriorFill
OST_StackedWalls
OST_MassGlazingAll
OST_MassFloorsAll
OST_MassWallsAll
OST_MassExteriorWallUnderground
OST_MassSlab
OST_HostTemplate
OST_MassFaceSplitter
OST_MassCutter
OST_ZoningEnvelope
OST_DividedSurface_DiscardedDivisionLines
OST_DividedSurfaceBelt
OST_TilePatterns
OST_AlwaysExcludedInAllViews
OST_DividedSurface_TransparentFace
OST_DividedSurface_PreDividedSurface
OST_DividedSurface
OST_RepeatingDetailLines
OST_RampsIncomplete
OST_TrussDummy
OST_ZoneSchemes
OST_AreaSchemes
OST_ProfileFamilies
OST_Blocks
OST_FootingAnalyticalGeometry
OST_Automatic
OST_ColumnAnalyticalGeometry
OST_FramingAnalyticalGeometry
OST_BasePointAxisZ
OST_BasePointAxisY
OST_BasePointAxisX
OST_SiteRegion
OST_SiteSurface
OST_Sewer
OST_Property
OST_ArcWallRectOpening
OST_DormerOpeningIncomplete
OST_SWallRectOpening
OST_StructuralFramingOpening
OST_ColumnOpening
OST_RiseDropSymbols
OST_MultistoryStairs
OST_HiddenStructuralConnectionLines_Deprecated
OST_StructuralConnectionHandler_Deprecated
OST_CoordinateSystem
OST_DSR_LeaderTickMarkStyleId
OST_DSR_InteriorTickMarkStyleId
OST_DSR_ArrowHeadStyleId
OST_DSR_CenterlineTickMarkStyleId
OST_DSR_CenterlinePatternCatId
OST_DSR_DimStyleHeavyEndCategoryId
OST_DSR_DimStyleHeavyEndCatId
OST_DSR_DimStyleTickCategoryId
OST_DSR_LineAndTextAttrFontId
OST_DSR_LineAndTextAttrCategoryId
OST_RailingRailPathExtensionLines
OST_RailingRailPathLines
OST_StairsSketchPathLines
OST_StairsTriserTags
OST_ComponentRepeaterSlot
OST_ComponentRepeater
OST_DividedPath
OST_IOSRoomCalculationPoint
OST_PropertySet
OST_AppearanceAsset
OST_StairStringer2012_Deprecated
OST_Stair2012_Deprecated
OST_RailingSystemTags
OST_RailingSystemTransition
OST_RailingSystemTermination
OST_RailingSystemRail
OST_RailingSystemTopRail
OST_RailingSystemHandRailBracket
OST_RailingSystemHandRail
OST_RailingSystemHardware
OST_RailingSystemPanel
OST_RailingSystemBaluster
OST_RailingSystemPost
OST_RailingSystemSegment
OST_RailingSystem
OST_AdaptivePoints_HiddenLines
OST_CeilingOpening
OST_FloorOpening
OST_RoofOpening
OST_WallRefPlanes
OST_StructLocationLineControl
OST_DimLockControlLeader
OST_AreaPolylines
OST_RoomPolylines
OST_InstanceDrivenLineStyle
OST_RemovedGridSeg
OST_IOSOpening
OST_IOSTilePatternGrid
OST_ControlLocal
OST_ControlAxisZ
OST_ControlAxisY
OST_ControlAxisX
OST_XRayConstrainedProfileEdge
OST_XRayImplicitPathCurve
OST_XRayPathPoint
OST_XRayPathCurve
OST_XRaySideEdge
OST_XRayProfileEdge
OST_ReferencePoints_HiddenLines
OST_PreviewLegendComponents
OST_LegendComponents
OST_ColorFillSchema
OST_AnnotationCrop
OST_FloorsAnalyticalGeometry
OST_WallsAnalyticalGeometry
OST_CropBoundary
OST_AxisZ
OST_AxisY
OST_AxisX
OST_Lights
OST_Cameras
OST_CurtaSystemFaceManager
OST_AreaReport_Arc_Minus
OST_AreaReport_Arc_Plus
OST_AreaReport_Boundary
OST_AreaReport_Triangle
OST_CurtainGridsSystem
OST_HostFinHF
OST_HostFinWall
OST_HostFinCeiling
OST_HostFinRoof
OST_HostFinFloor
OST_HostFin
OST_Divisions
OST_Catalogs
OST_DirectionEdgeLines
OST_Viewers
OST_Constraints
OST_DisplacementElements
OST_ReferenceViewerSymbol
OST_ModelText
OST_FaceSplitter
OST_MassingProjectionOutlines
OST_MassingCutOutlines
OST_Massing
OST_Reveals
OST_RailingBalusterRailCut
OST_RailingBalusterRail
OST_Railings
OST_CurtainWallMullionsCut
OST_AreaReference
OST_AreaInteriorFill
OST_RoomReference
OST_RoomInteriorFill
OST_Fixtures
OST_StairsStringerCarriage
OST_StairsAboveCut_ToBeDeprecated
OST_StairsIncomplete_Deprecated
OST_IOSNavWheelPivotBall
OST_IOSRoomComputationHeight
OST_IOSRoomUpperLowerLines
OST_IOSDragBoxInverted
OST_IOSDragBox
OST_Phases
OST_IOS_GeoSite
OST_IOS_GeoLocations
OST_IOSFabricReinSpanSymbolCtrl
OST_EPS_Future
OST_EPS_Temporary
OST_EPS_New
OST_EPS_Demolished
OST_EPS_Existing
OST_IOSMeasureLineScreenSize
OST_IOSRebarSystemSpanSymbolCtrl
OST_IOSRoomTagToRoomLines
OST_IOSAttachedDetailGroups
OST_IOSDetailGroups
OST_IOSSuspendedSketch
OST_IOSWallCoreBoundary
OST_IOSMeasureLine
OST_IOSArrays
OST_Curtain_Systems
OST_IOSBBoxScreenSize
OST_IOSSlabShapeEditorPointInterior
OST_IOSSlabShapeEditorPointBoundary
OST_IOSSlabShapeEditorBoundary
OST_IOSSlabShapeEditorAutoCrease
OST_IOSSlabShapeEditorExplitCrease
OST_IOSNotSilhouette
OST_FillPatterns
OST_CloudLines
OST_IOSRoomPerimeterLines
OST_IOSCuttingGeometry
OST_IOSCrashGraphics
OST_IOSGroups
OST_IOSGhost
OST_StairsSketchLandingCenterLines
OST_StairsSketchRunLines
OST_StairsSketchRiserLines
OST_StairsSketchBoundaryLines
OST_InvisibleLines
OST_IOSThinPixel_DashDot
OST_IOSThinPixel_Dash
OST_IOSThinPixel_Dot
OST_Extrusions
OST_IOS
OST_CutOutlines
OST_IOSThinPixel
OST_IOSFlipControl
OST_IOSSketchGrid
OST_IOSSuspendedSketch_obsolete
OST_IOSFreeSnapLine
OST_IOSDatumPlane
OST_IOSConstructionLine
OST_IOSAlignmentGraphics
OST_IOSAligningLine
OST_IOSBackedUpElements
OST_IOSRegeneratedElements
OST_Curves
OST_CeilingsProjection
OST_CeilingsCut
OST_RoofsProjection
OST_RoofsCut
OST_FloorsProjection
OST_FloorsCut
OST_DoorsGlassCut
OST_DoorsFrameMullionCut
OST_DoorsOpeningCut
OST_DoorsPanelCut
OST_WindowsOpeningCut
OST_WindowsSillHeadCut
OST_WindowsFrameMullionCut
OST_WindowsGlassCut
OST_WallsProjectionOutlines
OST_WallsCutOutlines
OST_IOSRegenerationFailure
OST_ScheduleViewParamGroup
OST_MatchSiteComponent
OST_MatchProfile
OST_MatchDetail
OST_MatchAnnotation
OST_MatchModel
OST_MatchAll
```

**Pull request merged**
