### PR TITLE
Colorize group types fixes

### PR DESCRIPTION
**Pull request by melnikovalex**
Hey Ehsan,

here are a couple of fixes for "Colorize Groups". Colors were generating in a strange way, I had to admire. Now it maybe not the cleanest way to do that but on practice, the result is much better.

I've also added Group Type selector as @Robbo1234 suggested here https://github.com/eirannejad/pyRevit/pull/712#issuecomment-672905096

Thank you for a new beta, going to try it out soon!

### CODE REVIEW

**Comment by eirannejad** [comment]
Thank you @melnikovalex Great PR. Pulled, reviewed, [made a few mods](https://github.com/eirannejad/pyRevit/commit/d50cffa81ce8421ee3fc3e19a15c26c9c46e8fc9), and merged into develop.

**Comment by Robbo1234** [comment]
Super work!

**Comment by Robbo1234** [comment]
Btw, I noticed that PyRevit Reset VG Override does't reset Revit Group Groups or Revit Nested Groups.

image

**Comment by Robbo1234** [comment]
Also, can PyRevit Colorized Groups Type avoid using the colour (Grey) when colourising.

**Pull request merged**
