### PR TITLE
added description to preflight class

### PR DESCRIPTION
**Pull request by jmcouffin**
as per https://github.com/eirannejad/pyRevit/pull/1103#issuecomment-761195706 @eirannejad

### CODE REVIEW

**Comment by jmcouffin** [comment]
concerning the UI, maybe using the shift+click to get it configured would be better?
@eirannejad, what do you think?

**Comment by jmcouffin** [comment]
I added this doughnut chart, who doesn't like doughnut ?
image
I couldn't figure out a way to wrap the legend and have it on the right side so that the doughnut stays on the left as well and the legend stays readable whatever the length of the description text.

**Comment by Robbo1234** [comment]
Hi there,

What is the procedure for getting this PyRevit Tool running on my Revit?

Thanking you in advance. Rob

**Comment by jmcouffin** [comment]
> Hi there,
> 
> What is the procedure for getting this PyRevit Tool running on my Revit?
> 
> Thanking you in advance. Rob
see instructions here. 
select the **develop** branch
https://discourse.pyrevitlabs.io/t/how-to-simple-install-and-use-of-a-different-branch-of-pyrevit-github/28

**Comment by Robbo1234** [comment]
FYI, I'm getting this error when I run the Preflight Checks tool.

*IronPython Traceback:*
Traceback (most recent call last):
File
"C:\Users\rob.cross\AppData\Roaming\pyRevit\Extensions\pyRevitTools.extension\pyRevit.tab\Project.panel\Preflight
Checks.pushbutton\script.py", line 3, in <module>
ImportError: cannot import preflight from pyrevit


*Script Executor Traceback:*
IronPython.Runtime.Exceptions.ImportException: cannot import preflight from
pyrevit
at IronPython.Runtime.Importer.ImportNestedModule(CodeContext context,
PythonModule module, String[] parts, Int32 current, List path)
at IronPython.Runtime.Importer.ImportFrom(CodeContext context, Object from,
String name)
at
Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame
frame)
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1
arg1)
at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime&
runtime)

**Comment by jmcouffin** [comment]
@Robbo1234 
did you install with:

`pyrevit clone develop --dest=C:\pyRevit\ --branch=develop`

and then 
attached it with

`pyrevit attach develop 279 --installed`

**Comment by eirannejad** [comment]
@Robbo1234 Already merged to `develop` branch and coming with the next release very soon. Planing to get it out this weekend :D

**Pull request merged**
