### PR TITLE
Update pyRevit CLI link and checksum

### PR DESCRIPTION
**Pull request by DailenG**

### CODE REVIEW

**Comment by eirannejad** [comment]
@DailenG What is this for? This data is usually updated when creating a new public release. What problem is this PR solving?

**Comment by DailenG** [comment]
> @DailenG What is this for? This data is usually updated when creating a new public release. What problem is this PR solving?

the nupkg does not install properly when running chocolatey command because it tries to download the wrong installer. The url listed generates a 404 error. So I updated with what I believe was the updated download and checksum and did a pull request. I'm guessing the version change was a minor one for a security patch.

image

**Comment by DailenG** [comment]
If there's another way to properly fix for pull request let me know and I'll help

**Comment by eirannejad** [comment]
Closing this until issue is investigated and fixed

**Pull request closed without merging**
