### PR TITLE
Russian localization Settings Window

### PR DESCRIPTION
**Pull request by dosymep**
I have added localization for Settings Window.

### CODE REVIEW

**Comment by jmcouffin** [comment]
Nice one
@eirannejad Do you see something in particular that would mess something else?
If not, we shall merge it. 
After that I can add the french version eventually

**Comment by dosymep** [comment]
> Nice one @eirannejad Do you see something in particular that would mess something else? If not, we shall merge it. After that I can add the french version eventually

I think need test in others engines, I have tested in IronPython 2.7.

**Comment by dosymep** [comment]
I think I will gradually translate, as this is a difficult task, plus there will be updates for the new revit, and there may be merge conflicts.

I think I will do the translation of windows in different Pull Requests.

**Comment by dosymep** [comment]
in a good way, you need to write a utility that would receive all window translations and compare translation identifiers

**Comment by eirannejad** [comment]
Merged into develop and will be released with next version very soon.  Thanks @dosymep @jmcouffin

**Pull request merged**
