### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jmcouffin**
@eirannejad 
Just took the text you send me and added an image of the contributors generated thks to contrib.rocks web app. I will PR this and wait for your go to merge

### CODE REVIEW

**Comment by eirannejad** [comment]
Ok. I've setup some time today to complete the docs and get this merged. Thank you

**Comment by jmcouffin** [comment]
> Ok. I've setup some time today to complete the docs and get this merged. Thank you

Excellent
Thks for the carving :)

**Comment by jmcouffin** [comment]
I suggest we had a link or a sample to a 'good' PR with a commented description

**Comment by eirannejad** [comment]
Merged into develop and will be released with next version very soon. Thanks@jmcouffin

**Pull request merged**
