### PR TITLE
Modification to Import/Export Family Configs

### PR DESCRIPTION
**Pull request by msmith320**
The original import and export family configs buttons did not account for shared parameters or parameters whose values were of type ElementId. The following scripts use the GUID of shared parameters and a specific string to keep track of the shared parameters and the Load Classification Type. The export button saves a txt file in addition to the yaml file with the same name and in the same directory. For import, make sure both the txt and yaml file are in the same directory.

### CODE REVIEW

**Comment by msmith320** [comment]
Please let me know if I need to make any changes.

**Comment by eirannejad** [comment]
Merged into `pr/1117` for review and will be merged into develop after

**Comment by msmith320** [comment]
@eirannejad Thanks for looking at the scripts. I commented a few adjustments in your commit. There was a naming issue with `DB.Electrical.ElectricalLoadClassification` and an issue with a variable being defined in an if block.

**Comment by eirannejad** [comment]
Ok great. This is already merged so would you mind sending a new PR to `develop` with your changes?

**Pull request merged**
