### PR TITLE
Fix #1732 import export family config

### LINKED ISSUE #1732: Export Family Config Fails
**Describe the bug**
Export Family Config fails with errors.

**To Reproduce**
1. Open a door family
2. Click on Family drop-down, then "Export Family Config"
3. Select location and parameters to export

**Expected behavior**
A YAML file generated with family parameters

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 11
 - pyRevit Version 4.8.12.22247
 - pyRevit Environment:
 `==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\ykaranfil\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\ykaranfil\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Users\ykaranfil\AppData\Roaming\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\ykaranfil\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.20.21 | Build: 20220726_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2020 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages`
`pyrevit env`

Choosing different parameters doesn't seems to make a difference.

### PR DESCRIPTION
**Pull request by jmcouffin**
Due to changes in the parameter storage and description in the API, the import and export family config tool needs some love to adjust to 2022+ new api

So far it is still a work in progress

### CODE REVIEW

**Comment by doctasayas** [comment]
Is there any movement on this ?

**Comment by jmcouffin** [comment]
@doctasayas would you like to help?

**Comment by jmcouffin** [comment]
Quite a few changes here. 
I will merge this one for now and see if someone manages to break it.

**Comment by sbeitelspacher** [comment]
> 📦 New public release are available for [4.8.13.23182+2215](https://github.com/eirannejad/pyRevit/releases/tag/untagged-47d1a64b11c2952394fc)

This link for the new release to fix this issue gives me an error. Is there a solution to this?

**Comment by jmcouffin** [comment]
> > 📦 New public release are available for [4.8.13.23182+2215](https://github.com/eirannejad/pyRevit/releases/tag/untagged-47d1a64b11c2952394fc)
> 
> This link for the new release to fix this issue gives me an error. Is there a solution to this?

this link is a year old, please use the latest release or one of the wip installers https://pyrevitlabs.github.io/pyrevitlabs/

**Comment by sarabjacobs** [comment]
> > > 📦 New public release are available for [4.8.13.23182+2215](https://github.com/eirannejad/pyRevit/releases/tag/untagged-47d1a64b11c2952394fc)
> > 
> > 
> > This link for the new release to fix this issue gives me an error. Is there a solution to this?
> 
> this link is a year old, please use the latest release or one of the wip installers https://pyrevitlabs.github.io/pyrevitlabs/

I downloaded the latest release and the wip installer and both still give me this error: 

Pyrevit Export-Import Family Config Issue

I am in r2023 btw.

**Comment by jmcouffin** [comment]
> > > > 📦 New public release are available for [4.8.13.23182+2215](https://github.com/eirannejad/pyRevit/releases/tag/untagged-47d1a64b11c2952394fc)
> > > 
> > > 
> > > This link for the new release to fix this issue gives me an error. Is there a solution to this?
> > 
> > 
> > this link is a year old, please use the latest release or one of the wip installers https://pyrevitlabs.github.io/pyrevitlabs/
> 
> I downloaded the latest release and the wip installer and both still give me this error:
> 
> Pyrevit Export-Import Family Config Issue
> 
> I am in r2023 btw.

please create a new issue, thks

**Pull request merged**
