### PR TITLE
Updated Mirrored Doors and Remove Underlay

### PR DESCRIPTION
**Pull request by gtalarico**
Revit 2015+2016 Compat added + Refactored Code

### CODE REVIEW

**Comment by eirannejad** [comment]
Thanks Gui

**Comment by gtalarico** [comment]
Hi Ehsan! 
I accidentally included my personal email in this pull request.
Are you able to delete it?

**Comment by eirannejad** [comment]
Nah. There is no Delete button for a Pull Request. But the files don't exist in the repo anymore.

**Comment by Robbo1234** [comment]
Would it be to add Mirrored Windows aswell?

**Comment by Robbo1234** [comment]
Also can we add this extra output results similar to PyRevit results dialog list the 

- Revit Element id,
- Room number
- Family Type
- Host Level

Refer to screen shot below:
image

Thanks

Rob

**Comment by gtalarico** [comment]
@Robbo1234 

> Would it be to add Mirrored Windows as well?
there is already a sep. script for windows on pyrevitplus:
https://github.com/gtalarico/pyrevitplus/blob/master/pyRevitPlus.tab/Misc%20Tools.panel/Sel%20Mirrored%20Windows.pushbutton/script.py

> Also can we add this extra output results
This should be an easy addition to https://github.com/gtalarico/pyrevitplus
Have you considered preparing a pull request with the changes you want? Here is the line:
https://github.com/gtalarico/pyrevitplus/blob/master/pyRevitPlus.tab/Misc%20Tools.panel/Sel%20Mirrored%20Doors.pushbutton/script.py#L28

**Comment by Robbo1234** [comment]
Yes, Mirrored Windows and I was thinking Casework Revit items would be a
great addition aswell.

**Comment by Robbo1234** [comment]
@gtalarico thanks for your response.

How does one go about preparing a PyRevit pull request to report the mirrored doors and windows in list format? Refer to screen shot:

image


Rob

**Pull request merged**
