### PR TITLE
UI theme

### PR DESCRIPTION
**Pull request by dosymep**
I have added theme support to ribbon icons. Issue #1834.
image
image

### CODE REVIEW

**Comment by dosymep** [comment]
Known Issues
icons do not change automatically, you need to reload Revit, or click Reload button.

When you change theme cache invalidation occurs by change its value. Maybe this solution is [hack](https://github.com/dosymep/pyRevit/blob/ui_theme/pyrevitlib/pyrevit/extensions/components.py#L375).
image

**Comment by dosymep** [comment]
Need to update icons?
<details>
  <summary>Sample</summary>
  
image


  ```
  
</details>

**Comment by jmcouffin** [comment]
This is all great.
So you are not creating .dark icons pngs on the fly.
What did you use in your sample image to create all icons?
Your hack seems acceptable IMHO

**Comment by jmcouffin** [comment]
You can add more commits for the icons .dark if you feel like it. I will look at it tomorrow if not

**Comment by dosymep** [comment]
i used this code to convert icons to dark mode

```csharp

static void CreateDarkIcon(string source)
{
    Bitmap image = (Bitmap) Image.FromFile(source);
    
    CreateBitmap(
        image,
        Color.FromArgb(235, 235, 235),
        Path.Combine(Path.GetDirectoryName(source), Path.ChangeExtension(source, ".dark.png")));
}

static void CreateBitmap(Bitmap source, Color color, string target)
{
    Bitmap output = new(source);
    for (int x = 0; x < source.Width; x++)
    {
        for (int y = 0; y < source.Height; y++)
        {
            Color pixel = source.GetPixel(x, y);
            output.SetPixel(x, y,
                pixel.A == 0
                    ? pixel
                    : Color.FromArgb(pixel.A, color.R, color.G, color.B));
        }
    }

    output.Save(target);
}

```

**Comment by jmcouffin** [comment]
All good @dosymep, great work!

**Comment by jmcouffin** [comment]
Added a Setter and docstrings to get and set methods

**Pull request merged**
